### ISSUE TITLE
Bug: Case-sensitive sorting

### ISSUE THREAD

**Issue by virginviolet** [FredHappyface/Android.EweSticker#73] opened 2024-04-24 17:38 UTC
### Description

Apologies for the cryptic title, it's the best I could think of.

Sorting is not truly alphabetic, as I see it, and it's not how files are sorted on Windows. I think it will become clear what I mean when you read on.

### Expected Behavior

I expected stickers to be sorted as following:

`Aa.png`, `bB.png`, `cc.png`, `DD.png`

### Actual Behavior

`Aa.png`, `DD,png`, `bB.png`, `cc.png`

## System Information

Please provide the following additional information about your system or
environment:

- Operating System (OS): Android
- OS Version: 14
- Project Version (if applicable): 20240322

**Comment by FredHappyface** [comment] 2024-08-25 13:02
Hi thanks for creating this issue, and apologies for taking so long to respond. IMO that is intended behaviour as many file systems are case sensitive (such as on linux). That said I do think there should be an option for a user to override this behaviour. I.e. Some config to enable case insensitive searching which would be a lot closer to what you are expecting. I'll add this to the todo 

(thanks for bearing with me on this 🙏)

**Comment by FredHappyface** [comment] 2024-08-25 14:36
Fixed in https://github.com/FredHappyface/Android.EweSticker/tree/20240825

**Closed by FredHappyface** 2024-08-25 14:36 UTC
Labels: bug

**Comment by virginviolet** [comment] 2024-08-27 16:34
Thank you!!

I was really confused before I submitted the issue on why it didn't sort the way I expected. I couldn't see the pattern. But, yeah, okay.

On Windows, in GUI, if you try to change the letter casing of a filename, nothing happens, it just reverts back. So you have to rename it to something else, like "My sticker RENAME ME.gif" and then rename it again, now with the original file name but with correct letter casing. It didn't cross my mind that case-sensitive sorting could have been intentional.

**Comment by FredHappyface** [comment] 2024-08-27 21:37
Ah yeah windows is pretty shoddy with filenames tbh. I believe the case insensitivity comes from the MSDOS days with FAT (File Allocation Table). Bit yeah Linux and Mac care about cases and "alphabetical" sorting uses this order (where uppercase letters are before lowercase) 

But yeah the workaround on windows is a massive pain! 

The new version is available on GitHub and Google play now (fdroid can take a few days). Hope this helps! :) And thanks for bringing this to my attention
